Setup Jest unit test
sajari/search-widgets pull request #230
Opened 2021-11-19 09:37 UTC by tuanddd

2021-11-19 12:51 UTC, zlatanpham submitted a review, later dismissed
Just need to add the config file to trigger the test in CI. e.g, adding `.github/workflows/test.yaml` with the following content:

```yml
name: Run test

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - name: Jest run
        run: |
          yarn
          yarn test:ci
```

2021-11-19 12:51 UTC, zlatanpham commented on package.json
> +    "test:watch": "jest --watch"
It'd be useful to print out test coverage info in the CI terminal

```suggestion
    "test": "jest",
    "test:watch": "jest --watch",
    "test:ci": "jest --env=jsdom --coverage --watchAll=false --maxWorkers=2",
```

2022-03-04 01:19 UTC, JasonBerry requested changes
General comment on test suite naming: "function should work correctly" isn't all that valuable as testing that something is working correctly is the point of having the tests in the first place, so it just adds noise to the test output. ;)

I think we can just put the function/module/class name in the describe block and leave it at that. You can also leave the describe block out entirely if it's not adding anything useful to the test output.

2022-03-04 01:19 UTC, JasonBerry commented on jest/setupFilesAfterEnv.js
> +import '@testing-library/jest-dom/extend-expect';
Should add `@testing-library/jest-dom` and `@testing-library/react` to dev dependencies rather than pulling them in transitively.

2022-03-08 02:57 UTC, JasonBerry approved these changes

2022-03-08 03:09 UTC, merged