feat: add tracking widget
sajari/search-widgets pull request #260
Opened 2022-04-06 13:12 UTC by tuanddd

## What is this
This PR adds a Tracking widget that takes in a simple list of DOM events (`onClick`, `onSubmit`, etc..) and calls the `EventTracking` track method with the provided data

## How to use
Take event `add_to_cart` for example, we'd have something like the following:
```js
/*
* product-template.liquid 
* (I assume that every Shopify themes has this file)
*/

<div data-widget="tracking">
  <script type="application/json">
      {
         "selector": "button#AddToCart",
         "event": "click",
         "metadata": {
              "id": "{{ product.id }}",
              "event": "add_to_cart"
         }
      }
  </script>
</div>
```

## Checklist
- [x] Implementation
- [x] Unit test

2022-04-08 12:57 UTC, tuanddd commented
The failing test is from overlay test, tried setting timeout to see if it can be resolved but no luck, maybe @zlatanpham can have another look.

2022-04-12 07:41 UTC, JasonBerry commented on src/tracking.tsx
> +      {['development', 'test'].includes(process.env.NODE_ENV ?? '') && (
Is our build process smart enough to nuke this from the production package?

2022-04-12 07:41 UTC, JasonBerry commented on src/defaults.ts
> +        selector: 'article h3 > a',
Should this be a default or just an example to be documented of _how_ it can be used?

2022-04-13 00:59 UTC, wwalser requested changes

2022-04-13 00:59 UTC, wwalser commented on src/tracking.tsx
> +          document.querySelectorAll(e.selector).forEach((element) => {
There's no reason to attach directly to the elements. Just attach a single event listen to the body and use event delegation to execute the callback. This will result in us attaching fewer event listeners in the customer DOM.

2022-04-13 02:08 UTC, wwalser commented
I was initially skeptical that this should be a widget since it doesn't actually inject DOM and is just behaviour. However, habitat widgets give us an easy way to hand the customer transparent, declarative, configuration.

2022-04-14 08:34 UTC, tuanddd commented on src/tracking.test.tsx
> +        </article>
@JasonBerry @wwalser 
This is just a workaround since using the actual `Results` component will force us to mock the request/response data in order for the UI to render the items. (which is just more setup work - not really a big deal)

2022-04-14 08:40 UTC, tuanddd commented
I've changed the tracking e2e test to a unit test because I feel like we're just really testing if the `track` method was called with the right event metadata.

2022-04-14 11:10 UTC, wwalser commented on src/tracking.test.tsx
> +        </article>
Perhaps add an inline comment so that others know then when they come across it.

2022-04-14 11:14 UTC, wwalser submitted a review, later dismissed

2022-04-15 00:43 UTC, zlatanpham reviewed
@tuanddd once Wes and Jason approved the change can you add document for the widget?

2022-04-15 00:43 UTC, zlatanpham commented on src/dev/Toolbar.tsx
> +  { name: 'Tracking', value: 'tracking' },
There is no view or document in the example so I have no clue what the widget does while seeing the blank page. Can we have at least a minimal version of info here? e.g, a fake add to cart button and a description to tell us that if clicking it will trigger a tracking event?

<img width="960" alt="image" src="https://user-images.githubusercontent.com/12707960/163497614-55cfe888-64db-4394-85d8-8b0eae657cf7.png">

2022-04-15 00:43 UTC, zlatanpham commented on src/tracking.tsx
> +    <SearchProvider searchOnLoad search={searchContext}>
Is `searchOnLoad` needed?

2022-04-15 03:23 UTC, zlatanpham commented on src/dev/Toolbar.tsx
> +  { name: 'Tracking', value: 'tracking' },
Also, the field `preset` seems redundant?

![image](https://user-images.githubusercontent.com/12707960/163513217-53855d93-46b2-4b95-99fc-bb2f42ace262.png)

2022-04-15 03:23 UTC, zlatanpham commented on src/dev/Toolbar.tsx
> +  { name: 'Tracking', value: 'tracking' },
Also, the field `preset` seems redundant?

![image](https://user-images.githubusercontent.com/12707960/163513217-53855d93-46b2-4b95-99fc-bb2f42ace262.png)

2022-04-15 08:56 UTC, tuanddd commented on src/tracking.tsx
> +    <SearchProvider searchOnLoad search={searchContext}>
It is actually because the tracking event will not fire if the `queryId` is not present and the only way to get that is to make a search request.

Although I've removed it per your comment because usually this widget is used along with other widgets that do make search requests so it's still valid.
<img width="1239" alt="Screen Shot 2022-04-15 at 15 56 02" src="https://user-images.githubusercontent.com/25856620/163549875-56ede2aa-767a-49ff-98d9-5e09c27968cf.png">

2022-04-15 10:42 UTC, zlatanpham commented on src/tracking.tsx
> +    <SearchProvider searchOnLoad search={searchContext}>
If so, I think we should keep it or find another way because there will be a case when the widget is solely on a page such as the order status page where there is no need for the appearance of other widgets.

2022-04-15 10:44 UTC, zlatanpham commented on src/tracking.tsx
> +    <SearchProvider searchOnLoad search={searchContext}>
Apparently, we can meet the issue on the tracking example. That is the exact issue I mentioned in the above comment.

![image](https://user-images.githubusercontent.com/12707960/163561896-eb7dca9a-2b28-481a-ba42-22e3a8a016fd.png)

2022-04-15 11:58 UTC, wwalser commented
I think Thanh's comment along with some Slack messages have revealed a fundamental misunderstanding about the API that we wish to design here. I'll need @JasonBerry to step in and help to clear up the best way of accomplishing what we want.

If a page has the following widget present:
```
<div data-widget="tracking">
  <script type="application/json">
      {
         "selector": "button#AddToCart",
         "event": "click",
         "metadata": {
              "id": "{{ product.id }}",
              "event": "add_to_cart"
         }
      }
  </script>
</div>
```

Then what should happen is that `click` events fired on a DOM node matching the `button#AddToCart` selector should have an `SearchIOAnalytics` event `add_to_cart` fired on them. The hardest part of this is determining the correct queryId to submit the event with. We want to fire the add_to_cart event with the most recent queryId in which the user clicked on a this result item — a result item for the item which they are not adding to their cart.

@JasonBerry is the best way to do this, to simply call `tracking.searchIOAnalytics.track(event, id, data)`? My reading of the code at [track](https://github.com/sajari/sdk-js/blob/master/src/tracking.ts#L208) is that it will look up the most recent result click for this item and use that `queryId`. 

If this is the correct way to do this, I think we need two changes in sdk-js. 
1. I note that it `track` only performs it's prevent event lookup for a small set of events, `FUNNEL_ENTRY_TYPES` which will need to be expanded for this PR to work.
2. I also note that the add-to-cart button will be clicked often for items which were navigated to via our search. Therefore firing a `console.error` when we can't find a queryId is probably the wrong move. I think I advocated the use of `console.error` previously. I believe we need an optional flag on `track` which will cause it to elicit a `console.error` when no `queryId` is found. We will use this flag internally when using track in a context where we expect a queryId to always exist.

2022-04-19 05:06 UTC, wwalser commented
I've spoken to Jason about this.
We shouldn't need a full context in order to submit tracking events. 

This should work:
```
const tracking = new EventTracking(id);
tracking.track(event, id, data);
```

As you've noticed, this call can be a bit noisy (console.error). This noise was intentional, but we agree that it is overkill for this use-case. 

When `.track()` is called, we use the unique id passed to look up previous interactions which have occurred using that same identifier. This is done in order to find the previously executed queryId which returned that result item. If one is found, that indicates that the user has previously interacted (clicked) on that item in a search result screen. Our use-cases for this lookup prior to this PR were all guaranteed. On a search result screen, not being able to find a queryId would be very strange and therefore merited a `console.error`. Now that we're using that same interface to perform ad-hoc event collection on items which may not have been navigated to via a search.io interface we need to quiet it down.

I'll make the change in sdk-js to only call `console.error` on event names we believe should be noisy.

2022-04-19 05:08 UTC, wwalser commented
I think the path forward is

1. I'll make changes in sdk-js and thread them through to sdk-react.
2. This PR will need to bump its sdk-react.
3. This PR needs to remove the context creation (instantiating a pipeline) and remove the use of useTracking. Instead, just instantiate the `EventTracking` interface directly.
4. Remove the arbitrary search query used to generate a queryId.

2022-04-19 09:06 UTC, tuanddd commented
Some notes:
- The tracking object needs to be passed to the `Pipeline` constructor so that the `bootstrap` method would be called which in turn properly set the `searchIOAnalytics`.
- Running the tracking example in dev mode will fail due to the lack of `queryId` variable, this is known and is waiting for the update to propagate from `sdk-js`.

2022-04-22 06:53 UTC, JasonBerry submitted a review, later dismissed
Bump sdk-js to 2.10.4 to grab the changes that silence the console.error's when a queryId isn't present yet.

2022-04-26 06:24 UTC, wwalser submitted a review, later dismissed

2022-04-26 08:14 UTC, JasonBerry approved these changes

2022-04-27 04:28 UTC, merged